export const ActionTypes = {
    CREATE_PROJECT: "CREATE_PROJECT",
    EDIT_PROJECT: "EDIT_PROJECT",
    DELETE_PROJECT: "DELETE_PROJECT",
    SET_PROJECTS: "SET_PROJETCS",
    FORM_TOGGLE_ENABLE: "ENABLE_EDIT_FORM",
    FORM_TOGGLE_DISABLE: "DISABLE_EDIT_FORM",
};