export const SourceControlActionType = {
    SET_SOURCE_CONTROL: "SET_SOURCE_CONTROL",
    CREATE_SOURCE_CONTROL: "CREATE_SOURCE_CONTROL",
    EDIT_SOURCE_CONTROL: "EDIT_SOURCE_CONTROL",
    DELETE_SOURCE_CONTROL: "DELETE_SOURCE_CONTROL",
    SOURCE_CONTROL_EDIT_ENABLE: "ENABLE_SOURCE_CONTROL",
    SOURCE_CONTROL_EDIT_DISABLE: "DISABLE_SOURCE_CONTROL",
};